<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class PasswordToUserEmail extends Notification
{
    use Queueable;
    private $password;
    /**
     * Create a new notification instance.
     */
    public function __construct($password)
    {
        $this->password = $password;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

   
    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
        ->line('Your password is: ' . $this->password)
        ->line('Note: This password is generated by the system!');
    }

    public function toArray(object $notifiable): array
    {
        return [
        
        ];
    }
}
